name: Deploy Node.js Application

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build

      # Read server IPs from a file and run deployment for each
      - name: Deploy to Servers
        run: |
          while IFS= read -r server_ip; do
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} root@$server_ip << 'EOF'
              cd /opt/azodu
              git pull
              npm install --production
              pm2 restart all
            EOF
          done < servers.txt
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
